apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zsoq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-zsoq@sha256:6e548d27d8703e78bfa2c7126a4bd44a7f2e099279467cd2d7fcae112bf6b0aa
        name: my-nodejs
        resources: {}
status: {}
